version: '3.3'

services:
  stack-demo:
    image: adoptopenjdk/maven-openjdk11
    volumes:
      - .:/home/application
    working_dir: /home/application
    command: "mvn clean install -U -Dspring.profiles.active=ci"
